apiVersion: v1
kind: Service
metadata:
  name: mamafi-io-cluster-ip-service
  namespace: mamafi-io-nsp
spec:
  type: ClusterIP
  selector:
    serviceName: mamafi-io-service-name
  ports:
    - port: 80
      targetPort: 3000